done yet to test
BDMADE/college pull request #31
Opened 2016-10-20 14:40 UTC by azizbabul

[taiga]{https://tree.taiga.io/project/hmtanbir-college/us/23?kanban-status=844212}

2016-10-22 14:37 UTC, hmtanbir requested changes
Please re solve merge conflict.

2016-10-22 14:37 UTC, hmtanbir commented on app/models/admin/tuition_fee.rb
> +  belongs_to :group
Add class name of group

2016-10-22 14:37 UTC, hmtanbir commented on db/schema.rb
> +  create_table "admin_tuition_fees_groups", force: :cascade do |t|
Why it is ?

2016-10-23 01:58 UTC, hmtanbir requested changes
Fix test

2016-10-23 01:58 UTC, hmtanbir commented on spec/controllers/admin/tuition_fees_controller_spec.rb
> +RSpec.describe Admin::TuitionFeesController, type: :controller do
Please fix this test.

2016-10-23 01:58 UTC, hmtanbir commented on spec/models/admin/tuition_fee_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Please add test for model.

2016-10-24 04:39 UTC, hmtanbir requested changes
Follow my comment and try to resolve it.

2016-10-24 04:39 UTC, hmtanbir commented on app/models/admin/tuition_fee.rb
> +  belongs_to :group, :class_name => Admin::AdmissionFeesStatus
Why do use `Admin::AdmissionFeesStatus` as class name ? Is this group  related to `Admin::AdmissionFeesStatus` model or `Admin::AdmissionTuitionGroup` model ?

2016-10-24 04:39 UTC, hmtanbir commented on config/routes.rb
> +Rails.application.routes.draw do
I don't understand about this routes. Do you understand ?!?

2016-10-24 04:39 UTC, hmtanbir commented on spec/controllers/admin/tuition_fees_controller_spec.rb
> +  group: FactoryGirl.create(:admin_admission_fees_status)
Do you follow your story ?? Or, you are working just like a blind man !!!

2016-10-24 04:39 UTC, hmtanbir commented on spec/views/admin/tuition_fees/new.html.erb_spec.rb
> +require 'rails_helper'
Fix this test

2016-10-24 04:39 UTC, hmtanbir commented on spec/views/admin/tuition_fees/show.html.erb_spec.rb
> +require 'rails_helper'
Fix this test.

2016-10-24 13:02 UTC, azizbabul commented on app/models/admin/tuition_fee.rb
> +  belongs_to :group, :class_name => Admin::AdmissionFeesStatus
please see it in reply in notification

2016-10-24 15:41 UTC, hta-wtag submitted a review, later dismissed

2016-10-24 15:41 UTC, hta-wtag commented on app/models/admin/tuition_fee.rb
> +  belongs_to :group, :class_name => class Admin::TuitionFeesGroup
Only class name

2016-10-24 15:41 UTC, hta-wtag commented on config/routes.rb
> +Rails.application.routes.draw do
:+1:

2016-10-26 03:12 UTC, hmtanbir commented on app/models/admin/tuition_fee.rb
> +  belongs_to :group, :class_name => Admin::TuitionFeesGroup
👍

2016-10-26 03:14 UTC, hmtanbir requested changes

2016-10-26 03:14 UTC, hmtanbir commented on app/models/admin/tuition_fees_group.rb
> +  has_many :adnin_tution_fees
spelling mistake, please check spelling.

2016-10-26 03:14 UTC, hmtanbir commented on spec/models/admin/tuition_fee_spec.rb
> +  it { is_expected.to validate_presence_of :name }
Please write test for uniqueness.

2016-10-26 03:20 UTC, hmtanbir commented on spec/controllers/admin/tuition_fees_controller_spec.rb
> +          Admin::NoticeBoardT.create!(valid_attributes)
Why do you need `Admin::NoticeBoardT` to test instead of `Admin::TuitionFee` ?

2016-10-26 03:25 UTC, hmtanbir commented on spec/controllers/admin/tuition_fees_controller_spec.rb
> +          group: FactoryGirl.create(:admin_tution_fees_group,name: "az")
It is okey.

2016-10-27 07:37 UTC, hmtanbir approved these changes

2016-10-27 07:38 UTC, merged