69 make a join model between tuition fees and admission fees status
BDMADE/college pull request #44
Opened 2016-11-16 13:05 UTC by azizbabul

[taiga]{https://tree.taiga.io/project/hmtanbir-college/us/69?kanban-status=844213}

2016-11-17 08:30 UTC, hmtanbir requested changes
Fix all comments.

2016-11-17 08:30 UTC, hmtanbir commented on db/migrate/20161112155558_add_attachment_image_to_admin_testimonials.rb
> -class AddAttachmentImageToAdminTestimonials < ActiveRecord::Migration
Why do you remove this migration file ?

2016-11-17 08:30 UTC, hmtanbir commented on db/migrate/20161114164404_create_join_table_admission_fees_statuses_tuition_fees.rb
> +     t.integer "admission_fees_status_id"
Why do you add this ?

2016-11-17 08:30 UTC, hmtanbir commented on db/schema.rb
> -    t.string   "image_file_name"
Why do you remove this from schema file ?

2016-11-17 08:30 UTC, hmtanbir commented on app/views/admin/tuition_fees/_form.html.erb
> +    <%= f.collection_select :group_id, Admin::TuitionFeesGroup.all,:id,:name%>
Don't change this. Because I already noticed that and have made an bug issue about this. So, Please revert this.

2016-11-17 15:20 UTC, azizbabul commented on db/schema.rb
> -    t.string   "image_file_name"
no idea , i did not do any thing

2016-11-17 15:22 UTC, azizbabul commented on db/migrate/20161112155558_add_attachment_image_to_admin_testimonials.rb
> -class AddAttachmentImageToAdminTestimonials < ActiveRecord::Migration
i did not touch all those at all but how ???? they are all in master right , why merging master does not update the master

2016-11-17 15:37 UTC, azizbabul commented on db/schema.rb
> -    t.string   "image_file_name"
i have checked the local master . files are there, i merged master to local join table but it is not updating  ---.now let me try git merge

2016-11-18 08:58 UTC, hmtanbir approved these changes

2016-11-18 09:10 UTC, merged