done with rspec
BDMADE/college pull request #51
Opened 2016-12-01 14:43 UTC by azizbabul

[taiga]{https://tree.taiga.io/project/hmtanbir-college/us/25?kanban-status=844212}

2016-12-02 04:46 UTC, hmtanbir requested changes
Please fix all comments.

2016-12-02 04:46 UTC, hmtanbir commented on app/views/admin/admission_processes/_admin_admission_process_image_detail_fields.html.erb
> +</div>
Add a new line

2016-12-02 04:46 UTC, hmtanbir commented on app/views/admin/admission_processes/_admin_admission_process_image_fields.html.erb
> +</div>
add a new line

2016-12-02 04:46 UTC, hmtanbir commented on db/migrate/20161130152451_create_admin_admission_process_image_details.rb
> +    add_index :admission_process_image_details,[:name]
How do you get it ?
Please follow story.

2016-12-02 04:46 UTC, hmtanbir commented on db/migrate/20161130152451_create_admin_admission_process_image_details.rb
> +      t.references :admission_process_image, foreign_key: true
Please add an index for this foreign key.

2016-12-02 16:22 UTC, azizbabul commented on db/migrate/20161130152451_create_admin_admission_process_image_details.rb
> +    add_index :admission_process_image_details,[:name]
fixed -- added in the table

2016-12-02 16:23 UTC, azizbabul commented on db/migrate/20161130152451_create_admin_admission_process_image_details.rb
> +      t.references :admission_process_image, foreign_key: true
it was there , i uncommentd it in line 4 and commented line 6

2016-12-03 15:22 UTC, hmtanbir commented on db/migrate/20161130152451_create_admin_admission_process_image_details.rb
> +      t.references :admission_process_image, foreign_key: true
I don't  know why you don't follow my instruction, please fix this error as soon as possible.

2016-12-03 15:23 UTC, hmtanbir commented on db/migrate/20161130152451_create_admin_admission_process_image_details.rb
> +    add_index :admission_process_image_details,[:name]
Nothing fixed yet, please fix, drop your database and re migration.

2016-12-03 15:25 UTC, hmtanbir commented on app/views/admin/admission_processes/show.html.erb
> +<% for i in @admin_admission_process.admin_admission_process_images%>
Use `each` block instead of `for` block

2016-12-03 15:26 UTC, hmtanbir requested changes
Please fix all of my comments.

2016-12-04 04:50 UTC, hmtanbir requested changes

2016-12-04 04:50 UTC, hmtanbir commented on db/migrate/20161130152326_create_admin_admission_process_images.rb
> +      t.references :admission_process, foreign_key: true
Please add an index, read story carefully again. If you read it, you will get the process of adding index.

2016-12-04 04:50 UTC, hmtanbir commented on db/migrate/20161130152451_create_admin_admission_process_image_details.rb
> +      t.references :admission_process_image, foreign_key: true
Please add an index, read story carefully again. If you read it, you will get the process of adding index.

2016-12-04 04:50 UTC, hmtanbir commented on app/views/admin/admission_processes/_admin_admission_process_image_fields.html.erb
> +</div>
add a new line.

2016-12-04 15:48 UTC, azizbabul commented on db/migrate/20161130152326_create_admin_admission_process_images.rb
> +      t.references :admission_process, foreign_key: true
done

2016-12-04 15:49 UTC, azizbabul commented on db/migrate/20161130152451_create_admin_admission_process_image_details.rb
> +      t.references :admission_process_image, foreign_key: true
done

2016-12-04 15:49 UTC, azizbabul commented on app/views/admin/admission_processes/_admin_admission_process_image_fields.html.erb
> +</div>
done

2016-12-05 05:40 UTC, hmtanbir requested changes

2016-12-05 05:40 UTC, hmtanbir commented on app/controllers/admin/abouts_controller.rb
> + layout "college/base"
Why do you add fronted layout in backend ?

2016-12-05 05:40 UTC, hmtanbir commented on app/views/admin/admission_processes/_admin_admission_process_image_fields.html.erb
> +</div>
Please add a new line.

2016-12-05 05:40 UTC, hmtanbir commented on db/migrate/20161130152326_create_admin_admission_process_images.rb
> +                   index: {name: :admission_process_image_}
Why do you use `underslash` end of the `admission_process_image_` word ?

2016-12-05 05:40 UTC, hmtanbir commented on db/migrate/20161130152451_create_admin_admission_process_image_details.rb
> +                   index: {name: :admission_process_image_details}
👍

2016-12-05 05:40 UTC, hmtanbir commented on config/routes.rb
> +  end
Please routes will be like as DRY!

2016-12-05 16:58 UTC, azizbabul commented on app/controllers/admin/abouts_controller.rb
> + layout "college/base"
changed

2016-12-05 17:01 UTC, azizbabul commented on app/views/admin/admission_processes/_admin_admission_process_image_fields.html.erb
> +</div>
added line

2016-12-05 17:01 UTC, azizbabul commented on db/migrate/20161130152326_create_admin_admission_process_images.rb
> +                   index: {name: :admission_process_image_}
corrected

2016-12-05 17:02 UTC, azizbabul commented on config/routes.rb
> +  end
DRY done

2016-12-06 08:39 UTC, hmtanbir approved these changes

2016-12-06 08:39 UTC, merged