50 make scholarship view
BDMADE/college pull request #61
Opened 2016-12-30 17:49 UTC by azizbabul

[taiga]{https://tree.taiga.io/project/hmtanbir-college/us/50?kanban-status=844212}

2017-01-02 05:33 UTC, hmtanbir requested changes
Write a spec test for the method.

2017-01-02 05:33 UTC, hmtanbir commented on app/helpers/frontend_helper.rb
> +  def scholarship_style_change(scholarship)
Please write a test for this `scholarship_style_change(scholarship)` method.

2017-01-02 12:50 UTC, azizbabul commented on app/helpers/frontend_helper.rb
> +  def scholarship_style_change(scholarship)
that i made a comment on this before actually i have no clue to write helpers  I waned to discuss of those

2017-01-08 04:37 UTC, hmtanbir approved these changes

2017-01-08 04:38 UTC, merged